language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls

services:
  - postgresql

before_script:
  - psql -c 'create database send_it;' -U postgres
  - sudo -u postgres psql -c "ALTER USER postgres PASSWORD 'v0k3ch!97';"

script:
  - pytest --cov=app/

after_success:
  - coveralls
