language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
  - pip install psycopg2-binary

services:
  - postgresql

before_script:
  - psql -c 'create database send_it_test;' -U postgres
  - export DB_TEST="dbname='send_it_test' host='localhost' port='5432' user='postgres' password=''"
  - export FLASK_ENV=testing
#  email variables have been set on travis .env

script:
  - pytest --cov=app/

after_success:
  - coveralls
